name: e_grocery
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  flutter_screenutil: ^4.0.0
  provider: ^4.3.2+3
  flutter_svg: ^0.19.0
  syncfusion_flutter_charts: ^18.3.53
  http: ^0.12.2
  flutter_staggered_grid_view: ^0.3.2
  #  fl_chart: ^0.12.1
  #  charts_flutter: ^0.9.0
  device_preview: ^0.5.5
  #  splashscreen: ^1.3.5
  shared_preferences: ^0.5.12+4
  string_similarity: ^1.1.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.8.1

flutter_icons:
  android: true
  ios: true
  image_path: "icon_assets/ss_icon.png"
  adaptive_icon_background: "#eaedf7"
  adaptive_icon_foreground: "icon_assets/ss_icon_responsive.png"



# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/pnp/
    - assets/shoprite/
    - assets/woolworths/
    - assets/images/
    - assets/main_menu/
    - assets/images/clothing/
    - assets/grocery_card_svg/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Montserrat
      fonts:
        #        - asset: fonts/montserrat/
        - asset: fonts/montserrat/Montserrat-Black.ttf
        - asset: fonts/montserrat/Montserrat-ExtraBold.ttf
        - asset: fonts/montserrat/Montserrat-Light.ttf
        - asset: fonts/montserrat/Montserrat-Medium.ttf
        - asset: fonts/montserrat/Montserrat-Regular.ttf
        - asset: fonts/montserrat/Montserrat-SemiBold.ttf
    #       - asset: fonts/Schyler-Italic.ttf
    #         style: italic
    - family: ClickerScript
      fonts:
        #        - asset: fonts/clickerscript/
        - asset: fonts/clickerscript/ClickerScript-Regular.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
